spring.thymeleaf.cache: false
spring:
  config:
    import: secret.properties
server:
  port: 443
  ssl:
    enabled: true
    enabled-protocols:
      - TLSv1.1
      - TLSv1.2
    key-store: "classpath:publickey.p12"
    key-store-password: ${PASSWORD}
    key-store-type: "PKCS12"
